### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by aiqinxuancai** [gunpal5/Google_GenerativeAI#1]
Version:0.1.9
I can use this key in local curl and it works fine. It is difficult to determine the specific cause of the error based on the information provided in the exception.
![image](https://github.com/gunpal5/Google_GenerativeAI/assets/4475018/83bc4854-c0db-4441-9cfe-2c907ae62577)

**Comment by gunpal5** [comment]
I think its due to Service Unavailable (HTTP Code 500) issue.

I fixed the error message. Please try again with version 0.1.10

**Comment by aiqinxuancai** [comment]
> I think its due to Service Unavailable (HTTP Code 500) issue.
> 
> I fixed the error message. Please try again with version 0.1.12

Thank you, I have seen the specific reason for the output. It seems that API access is restricted by region.
```
{
  "error": {
    "code": 400,
    "message": "User location is not supported for the API use.",
    "status": "FAILED_PRECONDITION"
  }
}
```

**Comment by gunpal5** [comment]
Can you try to change the APIs version to v1 instead of v1beta? 

`
var model = new GenerativeModel(apiKey){
Version = "v1"
}
`

Version v1 doesn't support function calling.
