### ISSUE TITLE
程式修正

### ISSUE THREAD

**Issue by ghost** [gunpal5/Google_GenerativeAI#2]
原程式碼
public static Content FormatGenerateContentInput(string @params)
{
    var parts = new[]{new Part(){Text = @params}};
    return new Content(parts, Roles.User);
}
Role永遠都只有user

應該修正多加string role參數(其它引用地方也需修正)
public static Content FormatGenerateContentInput(string @params,string  role)
{
    var parts = new[] { new Part() { Text = @params } };
    return new Content(parts,  role);
}
否則會出現錯誤！

**Comment by gunpal5** [comment]
Added in [src/GenerativeAI/Extensions/RequestExtensions.cs](https://github.com/gunpal5/Google_GenerativeAI/commit/a61178da1c85c48e19bfc326713a45606605914c)
