### ISSUE TITLE
Question About Defining Custom Safety Settings in Version 1.12

### ISSUE THREAD

**Issue by VinceMack** [gunpal5/Google_GenerativeAI#3]
In your [Enums.cs file](https://github.com/gunpal5/Google_GenerativeAI/blob/0d5c882668cc4a4b7c6f910606a0974a8fb7184e/src/GenerativeAI/Types/Enums.cs#L4), I noticed that you’ve defined enumeration types for safety settings. However, it appears there isn’t a straightforward way to specify these safety settings for the model which, from what I can tell, appears to be using the defaults from Google. Does version 1.12 of the your unofficial SDK accommodate customizing the safety settings?

**Comment by gunpal5** [comment]
Hi,

You would need to create a request manually to specify the safety settings. e.g.
`csharp
var model = new GenerativeModel(apiKey);

model.GenerateContentAsync(new GenerateContentRequest()
{
    Contents = new[] { RequestExtensions.FormatGenerateContentInput("Tell me about terrorism") },
    SafetySettings = new[]
    {
        new SafetySetting()
        {
            Category = HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
            Threshold = HarmBlockThreshold.BLOCK_ONLY_HIGH
        }
    }
});`

if you have any suggestion to simplify this, I would happily implement it into the library.
