### ISSUE TITLE
Proxy support for supported region

### ISSUE THREAD

**Issue by aadi1295** [gunpal5/Google_GenerativeAI#4]
Hello,
Thank you for this API. 
It's working fine locally as Gemini API support my local region. However on server deployment it is giving me this error. My server is in Netherlands and according to this [https://ai.google.dev/available_regions#available_regions](url) Netherlands is not supported. Can you please add functionality to use proxy so that it can use supported region. Thank you again.
```
{
  "error": {
    "code": 400,
    "message": "User location is not supported for the API use.",
    "status": "FAILED_PRECONDITION"
  }
}
```

**Comment by gunpal5** [comment]
I would suggest to move server to any supported location: https://ai.google.dev/available_regions

Proxy would not be a reliable solution.

if you still want to use proxy with the library then just initialize a HttpClient instance with Proxy and pass it to the model: 

```csharp
var handler = new HttpClientHandler()
{
    Proxy = new WebProxy("IP:PORT")
    {
        Credentials = new NetworkCredential("UserName","Password")
    }    
};
var httpClient = new HttpClient(handler);

var model = new GenerativeModel(apiKey,client:httpClient);
//var model = new GeminiProModel(apiKey, client: httpClient)
//var visionModel = new GeminiProVision(apiKey, client: httpClient);

```
